### ISSUE TITLE
Can't get it work with 1.3.3 / 0.11.14

### ISSUE THREAD

**Issue by alari** [scullxbones/akka-persistence-mongo#127]
I'm trying plugin version `1.3.3` with rx `0.11.14` and see this:

```
java.lang.NoSuchMethodError: reactivemongo.api.indexes.Index$.$lessinit$greater$default$8()Lreactivemongo/bson/BSONDocument;
        at akka.contrib.persistence.mongodb.RxMongoSnapshotter.snaps(RxMongoSnapshotter.scala:60)

```

**Comment by scullxbones** [comment]
Damn.  I think `1.3.3` ended up being a re-release of `1.3.2`.  Will get `1.3.4` out this evening.

**Comment by scullxbones** [comment]
Got `1.3.4` out
